### ISSUE TITLE
Enhance environment variables THUB_VAR_xyz

### ISSUE THREAD

**Issue by eistrati** [tfxor/terrahub#1078]
# Feature Report

## Describe the Feature
Enhance environment variables THUB_VAR_xyz to be leveraged in each thread of terrahub cli

## To Reproduce
Project Config:
```yaml
project:
  name: TerraHub
  code: 'abcd1234'
  env:
    variables:
      THUB_VAR_AWS_REGION: us-east-1
      THUB_VAR_AWS_ACCOUNT: 123456789012

template:
  terraform:
    backend:
      s3:
        key: terraform/tfxor/terrahub/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
        workspace_key_prefix: terraform_workspaces
        bucket: tfstate-logs-${tfvar.terrahub["env"]["THUB_VAR_AWS_REGION"]}-${tfvar.terrahub["env"]["THUB_VAR_AWS_ACCOUNT"]}
        region: ${tfvar.terrahub["env"]["THUB_VAR_AWS_REGION"]}
    required_providers:
      aws:
        source: hashicorp/aws
        version: 3.30.0
  provider:
    aws:
      region: ${tfvar.terrahub["env"]["THUB_VAR_AWS_REGION"]}
      allowed_account_ids:
        - ${tfvar.terrahub["env"]["THUB_VAR_AWS_ACCOUNT"]}
```

Component Config:
```yaml
component:
  name: s3_bucket
build:
  env:
    variables:
      THUB_BUILD_OK: false
      THUB_BUILD_S3_DEPLOY: s3://tfstate-logs-${THUB_VAR_AWS_REGION}-${THUB_VAR_AWS_REGION}/deploy/tfxor/terrahub
      THUB_BUILD_INDEX_FILE: index.txt
      THUB_BUILD_DOTENV_FILE: .env
      THUB_BUILD_COMPILE_FILE: ./bin/compile.sh
      THUB_BUILD_LOCAL_PATH: ./build
      THUB_BUILD_SOURCE_PATH: ./src ./webpack ./index.html
  phases:
    build:
      commands:
        - 'echo "[BUILD] Running build step"'
        - ./scripts/build.sh || { echo >&2 "Failed to run `build.sh`. Aborting..."; exit 1; }
```

## Expected Behavior
1. At runtime, we expect project config to replace all `$tfvar.terrahub["env"]` variables with corresponding environment variables
2. At runtime, we expect component config to be able to replace environment variables that are defined with corresponding values (if environment variable is missing, leave the component's config as it is)
